_format_version: "2.1"
services:
  - name: auth-v1
    url: http://supabase-auth:9999
    routes:
      - name: auth-v1-routes
        paths:
          - /auth/v1
        strip_path: true
        
  - name: rest-v1
    url: http://supabase-rest:3000
    routes:
      - name: rest-v1-routes
        paths:
          - /rest/v1
        strip_path: true

  - name: realtime-v1
    url: http://supabase-realtime:4000
    routes:
      - name: realtime-v1-routes
        paths:
          - /realtime/v1
        strip_path: true

  - name: storage-v1
    url: http://supabase-storage:5000
    routes:
      - name: storage-v1-routes
        paths:
          - /storage/v1
        strip_path: true
